name: Scrape Kings League WebPage

on:
  workflow_dispatch:
    
  schedule:
    - cron: "0 */1 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: |
          node scraping/index.js
          git config --global user.email "jose.gomez14@udea.edu.co"
          git config --global user.name "jose-scraper-bot"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] Update Kings League Database"
          git push origin main
